[package]
name = "rpc-json-client"
version = "0.1.0"
authors = ["Urkel Engineering <engineering@urkellabs.com>"]
edition = "2018"

[dependencies]

# Unknown External
futures = "0.3.1"
async-std = "1.2.0"
hyper = "0.13.0-alpha.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
surf = "1.0.3"
