[package]
name = "rpc-json-client"
version = "0.1.0"
authors = ["kilpatty <sean@urkel.io>"]
edition = "2018"

[dependencies]

# Unknown External
futures-preview = "0.3.0-alpha.18"
hyper = "0.13.0-alpha.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
runtime = "0.3.0-alpha.7"
surf = "1.0.2"
